version: '3'
services:
  holder:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start --arg-file ./configs/holder.yml
        -e http://holder:3000
        --webhook-url http://webhook-listener:8080
    depends_on:
      - webhook-listener

  issuer:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0
    ports:
      - 3002:3000
      - 3003:3001
    volumes:
      - ./configs:/home/indy/configs:z
    command: >
      start --arg-file ./configs/issuer.yml
        -e http://issuer:3000
        --webhook-url http://webhook-listener:8080
    depends_on:
      - webhook-listener

  webhook-listener:
    image: mendhak/http-https-echo:18
    environment:
      - HTTP_PORT=8080

  demo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.demo
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=holder:3000,issuer:3000
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - HOLDER=http://holder:3001
      - ISSUER=http://issuer:3001
    depends_on:
      - holder
      - issuer
